# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- typescript

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

# - task: ArchiveFiles@2
#   inputs:
#     rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
#     includeRootFolder: false

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Windows Azure MSDN - Visual Studio Ultimate(b0515714-0ea1-43d4-ae9b-4d87afe8e8a3)'
    appType: 'webApp'
    WebAppName: 'xkcd2'
    deployToSlotOrASE: true
    ResourceGroupName: 'Default-Web-EastUS'
    SlotName: 'staging'
    # packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'