# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: xkcd2-serverless

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: azure
  location: West US 2

plugins:
  - serverless-azure-functions
  - serverless-express

# you can add packaging information here
package:
  #  include:
  #    - include-me.js
  #    - include-me-dir/**
  exclude:
    #    - exclude-me.js
    - src/**
    - local.settings.json
    - .vscode/**

functions:
  app:
    handler: dist/app.handler
    events:
      # - http:
      #   path: /
      #   method: GET
      #   cors: true
      - http:
        path: /{+proxy}
        method: ANY
  # index:
  #   handler: hello.handler
  #   events:
  #     - http: true
  #       x-azure-settings:
  #         authLevel: anonymous
  #     - http: true
  #       x-azure-settings:
  #         direction: out
  #         name: res
  # goodbye:
  #   handler: goodbye.handler
  #   events:
  #     - http: true
  #       x-azure-settings:
  #         authLevel: anonymous
  #     - http: true
  #       x-azure-settings:
  #         direction: out
  #         name: res
# The following are a few examples of other events you can configure:
#
# events:
#   - queue: YourQueueName
#     x-azure-settings:
#       connection : StorageAppSettingName
#   - blob:
#     x-azure-settings:
#       name: bindingName
#       direction: in
